services:
  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - './wordpress:/var/www/html'
      - './yourplugin.php:/var/www/html/wp-content/plugins/yourplugin/yourplugin.php'
      - './src:/var/www/html/wp-content/plugins/yourplugin/src'
      - './vendor:/var/www/html/wp-content/plugins/yourplugin/vendor'
      - './nginx/conf.d/site.conf:/etc/nginx/conf.d/site.conf'
    networks:
      - wordpress
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    depends_on:
      - mysql
      - wordpress
  mysql:
    image: mysql:8
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - wordpress
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: wordpress
    ports:
      - '3306:3306'
  wordpress:
    image: wordpress-laravel:php8.1-fpm
    build:
      context: ./docker/wordpress
      dockerfile: Dockerfile
    depends_on:
      - mysql
    volumes:
      - './wordpress:/var/www/html'
      - './yourplugin.php:/var/www/html/wp-content/plugins/yourplugin/yourplugin.php'
      - './src:/var/www/html/wp-content/plugins/yourplugin/src'
      - './vendor:/var/www/html/wp-content/plugins/yourplugin/vendor'
      - './php/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini'
    networks:
      - wordpress
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DEBUG: true
  cli:
    image: wordpress-laravel:cli-php8.1
    build:
      context: ./docker/cli
      dockerfile: Dockerfile
    depends_on:
      - wordpress
      - mysql
      - nginx
    networks:
      - wordpress
    volumes:
      - './wordpress:/var/www/html'
      - './yourplugin.php:/var/www/html/wp-content/plugins/yourplugin/yourplugin.php'
      - './src:/var/www/html/wp-content/plugins/yourplugin/src'
      - './vendor:/var/www/html/wp-content/plugins/yourplugin/vendor'
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DEBUG: true
networks:
  wordpress:
    driver: bridge
volumes:
  mysql:
    driver: local